# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_phone',
            old_name='personcode',
            new_name='contact',
        ),
    ]
